services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=devUser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=movies
    ports:
      - '5431:5432'